bot:
  start: 
    buttons:
      - "Новый диалог"
    text: "Привет! Я бот-сценарист. Я использую для ответов YandexGPT.\nЛимит токенов для каждой сессии равен 200\nДля начала напиши: Новый диалог"

  new:
    buttons:
      - "Страшилка"
      - "Комедия"
      - "Фантастика"
    text: "Для начала выбери жанр своей истории:"
  
  style:
    buttons:
      - "Исследовательница"
      - "Киборг"
      - "Чародейка"
      - "Хакер"
    text: "Выбери главного персонажа твоей истории:"

  character:
    buttons:
      - "Современный мир"
      - "Постапокалипсис"
      - "Далекое будущее"
      - "Космос"
      - "Средневековье"
    text: "Выбери сеттинг персонажа твоей истории:\n\nСовременный мир - сценарии из повседневной жизни, работы и технологий\n\nПостапокалипсис - выживание в мире после глобальной катастрофы\n\nДалекое будущее - приключения в продвинутом технологическом обществе\n\nКосмос - исследования космоса\n\nСредневековье - рыцари, замки, и волшебные приключения"

  setting:
    buttons:
      - "Сгенерировать"
    text: "Настройки заданы"

  all:
    triger: "Вся история"

    user_not_found: "Пользователь не найден"

  master:
    buttons:
      - "Дальше"
      #- "Вся история"
      - "Новый диалог"
      - "Статистика"
      - "Токены"


  
models:
  start:
    text: "Бот запущен"

  db_conn:
    error: "Произошла ошибка при подключении к базе данных. Повторите попытку позже"
    owner: "Ошибка подключения к базе данных\nError: {0}"

  db_check:
    error1: "Произошла ошибка при подключении к базе данных. Проверьте настройки базы данных" 
    owner1: "Ошибка первоначального подключения к базе данных\n{0}"

    owner2: "Ошибка при проверке таблиц базы данных\n{0}"

  new_session:
    error: "Произошла ошибка при создание сессии. Повторите попытку позже"
    owner: "Ошибка при создание сессии\n{0}"

    sessions_limit: "Лимит диалогов исчерпан"
    users_limit: "Лимит пользователей исчерпан"

  save_style:
    error: "Произошла ошибка при сохранении жанра. Повторите попытку позже"
    owner: "Ошибка при сохранении жанра\n{0}"

  save_character:
    user_not_found: "Пожалуйста проверьте что вы указали стиль"
    error: "Произошла ошибка при сохранении героя. Повторите попытку позже"
    owner: "Ошибка при сохранении героя\n{0}"

  save_setting:
    user_not_found: "Пожалуйста проверьте что вы указали стиль"
    error: "Произошла ошибка при сохранении сеттинга. Повторите попытку позже"
    owner: "Ошибка при сохранении сеттинга\n{0}"

  save_history:
    user_not_found: "Пользователь не найден, пожалуйста проверьте что вы указали жанр, героя и сеттинг"
    owner: "Ошибка при сохранении истории\n{0}"
    
  load_history:
    user_not_found: "Пользователь не найден, пожалуйста проверьте что вы указали жанр, героя и сеттинг"

  count_tokens:
    bad_response: "Не удалось получить ответ от нейросети"
    bad_connection: "Не удалось подключиться к нейросети"
    owner_bad_connection: "Ошибка подключения: {0}"

    unexpected_error: "Произошла непредвиденная ошибка"
    owner_unexpected_error: "Непредвиденная ошибка при подключении: {0}"

  gpt_request:
    not_style: "Пожалуйста укажите жанр"
    not_character: "Пожалуйста укажите героя"
    not_setting: "Пожалуйста укажите сеттинг"

    too_long: "Текст запроса слишком длинный!"
    token_limit: "Лимит токенов исчерпан"

    bad_response: "Не удалось получить ответ от нейросети"
    bad_connection: "Не удалось подключиться к нейросети"
    owner_bad_connection: "Ошибка подключения: {0}"

    unexpected_error: "Произошла непредвиденная ошибка"
    owner_unexpected_error: "Непредвиденная ошибка при подключении: {0}"

    text_end: "\n\nИспользовано токенов: {0}/{1}"

  statistics:
    triger: "Статистика"
    text: "Статистика за последние 7 дней:\n— Самый популярный жанр: {0}\n— Запросов: {1}\n\nСамый популярный герой: {2}\nЗапросов: {3}\n\nСамый популярный сеттинг: {4}\nЗапросов: {5}\n\nА последние запросы выглядели так:\n"

    last_messages: "— {0}\n"

  tokens:
    triger: "Токены"
    text: "Использовано токенов для этой сессии {0}/{1}"

    error: "Сессии не найдены"

  set_debug_mode:
    user_not_found: "Пользователь не найден"

    enable: "Режим отладки включен"
    disable: "Режим отладки выключен"


  get_token:
    error: "Ошибка при сохранение токена в config.yaml: \n{0}"
    owner: "Ошибка при сохранении токена в config.yaml: \n{0}"

    error2: "Не удалось получить IAM-токен"
    owner2: "Ошибка получения IAM-токена"